name: Publish Approved Pull Requests
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has-permissions: ${{ steps.checkPermissions.outputs.require-result || github.event.pull_request.user.login == github.repository_owner }}
    steps:
      - name: Check permissions
        id: checkPermissions
        # Only run permissions check if this is triggered by a review
        if: github.event_name == 'pull_request_review'
        uses: actions-cool/check-user-permission@v2
        with:
          require: "write"

  publish:
    needs: check
    if: needs.check.outputs.has-permissions == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Build package
        run: deno task build:npm

      - run: npx pkg-pr-new publish --compact './packages/*'
