name: Deno test
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x
    - name: Typecheck
      run: deno check mod.ts
    - name: Test
      run: deno test -A src/